
print("                  --------")
print("               --          --")
print("             -                 -")
print("           -    __--__   __--__  -")
print("          -       |        |      -")
print("          -       |        |      -")
print("          -             )         -")
print("          -      ____________     -")
print("           -     \\          /    -")
print("            --    \\        /   --")
print("               --- \\______/ ---")
print("                   --------")
print("                       |")
print("                       |")
print("                       |")
print("                      /|\\")
print("                     / | \\")
print("                    /  |  \\")
print("                   /   |   \\")
print("                  /    |    \\")
print("                 /     |     \\")
print("                /      |      \\")
print("               /       |       \\")
print("              /        |        \\")
print("             /         |         \\")
print("            /          |          \\")
print("                       |")
print("                       |")
print("                      /\\")
print("                     /  \\")
print("                    /    \\")
print("                   /      \\")
print("                  /        \\")
print("                 /          \\")
print("                /            \\")
print("               /              \\")
print("              /                \\")
print("             /                  \\")
